lib_manager/config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get "/pages/*page", to: "pages#show"

  get "signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, expert: [:index, :new] do
    resources :borrow_books, only: [:create, :destroy]
    resources :follow_books, only: [:create, :destroy]
    resources :follow_users, only: [:index, :create, :destroy]
    resources :follow_authors, only: [:create, :destroy]
    resources :ratings, only: [:create, :update]
  end
  resources :authors, only: :show
  resources :books, only: [:index, :show] do
    resources :comments, only: :create
  end
  resources :categories, only: :show do
    resources :books, only: [:index, :show]
  end

  namespace :admins do
    resources :users
    resources :books
    resources :publishers
    resources :authors
    resources :categories
    resources :borrow_books, only: [:index, :update, :destroy]
  end
end

lib_manager/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :downcase_email

  scope :sort_by_create_at, -> {order created_at: :desc}
  scope :search_by_name, -> search{where "name LIKE ?", "%#{search}%"}
  scope :search_by_permision, -> search_permision{where is_admin: search_permision}

  mount_uploader :image, AvatarUploader

  has_many :comments
  has_many :ratings
  has_many :borrow_books

  has_many :relationships, as: :ownerable
  has_many :books, through: :relationships,
    source_type: Book.name, source: :targetable
  has_many :following_author, through: :relationships,
    source_type: Author.name, source: :targetable

  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "ownerable_id", dependent: :destroy
  has_many :following, through: :active_relationships,
    source_type: User.name, source: :targetable

  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "targetable_id", dependent: :destroy
  has_many :followers, through: :passive_relationships,
    source_type: User.name, source: :ownerable

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
      uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: 6}, allow_nil: true
  validates :image, presence: true
  validates :phonenumber, presence: true,
    length: {maximum: 10}
  validates :address, presence: true

  has_secure_password

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def current_user? current_user
    self == current_user
  end

  def follow_book book
    books << book
  end

  def unfollow_book book
    books.destroy book
  end

  def following_book? book
    books.include? book
  end
  
  def following_user other_user
    following << other_user
  end

  def unfollow_user other_user
    following.destroy other_user
  end

  def following_user? other_user
    following.include? other_user
  end

  def follow_author author
    following_author << author
  end

  def following_author? author
    following_author.include? author
  end

  def unfollow_author author
    following_author.destroy author
  end

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

    def digest string
      cost = ActiveModel::SecurePassword.min_cost ?
        BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def to_csv options = {}
      CSV.generate options do |csv|
        csv << column_names
        all.each do |user|
          csv << user.attributes.values_at(*column_names)
        end
      end
    end
  end

  private
  def downcase_email
    email.downcase!
  end
end

lib_manager/app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  layout "application_admin"

  before_action :logged_in_user, :verify_admin
  before_action :find_user, except: [:index, :new, :create]

  def index
    @users = if params[:search].present? && params[:search_by_permision].present?
      User.search_by_name(params[:search])
        .search_by_permision(params[:search_by_permision])
    elsif params[:search].present?
      User.search_by_name(params[:search])
    elsif params[:search_by_permision].present?
      User.search_by_permision(params[:search_by_permision])
    else
      User
    end.sort_by_create_at.paginate page: params[:page]
    respond_to do |format|
      format.html
      format.js
      format.xls {send_data @users.to_csv(col_sep: "\t")}
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "controllers.users.admin_create_user"
      redirect_to admins_users_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      redirect_to admins_users_path
      flash[:success] = t "controllers.users.edit_user_success"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = t "controllers.users.admin_delete"
    redirect_to admins_users_path 
  end

  private
  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "controllers.users.user_not_exist"
      redirect_to admins_users_path
    end
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :address, :phonenumber, :is_admin, :image
  end
end

lib_manager/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include CheckObject

  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :check_user_exist, only: [:show, :edit, :update]

  def show
    @users = @user.following.pagination params[:page]
    @borrow_books = @user.borrow_books.pagination params[:page]
    @authors = @user.following_author.pagination params[:page]
    @books = @user.books.pagination params[:page]
    if params[:relationship].present?
      @users = if params[:relationship] == "following"
        @user.following.pagination params[:page]
      elsif params[:relationship] == "followers"
        @user.followers.pagination params[:page]
      end
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash.now[:success] = t "controllers.users.create_success"
      redirect_back_or @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash.now[:success] = t "controllers.users.edit_success"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :image, :address, :phonenumber
  end

  def check_user_exist
    @user = User.find_by id: params[:id]
    check_object @user
  end

  def correct_user
    @user = User.find_by id: params[:id]
    redirect_to root_url unless current_user.current_user? @user
  end
end

lib_manager/app/views/users/_author_followed.html.erb
<% @authors.each_slice Settings.slice do |list_authors| %>
  <div class="row">
    <% list_authors.each do |author| %>
      <div class="block-book col-xs-6">
        <div class="block thumbnail">
          <div class="image col-xs-4">
            <%= link_to image_for(author, size: Settings.size), author_path(author) %>
          </div>
          <div class="caption col-xs-8">
            <div class="name">
              <span><%= t "views.books.indexs.name" %></span>
              <span><%= link_to author.name, author_path(author) %></span>
            </div>
            <div class="address">
              <span><%= t "views.books.indexs.author" %></span>
              <span><%= author.address %></span>
            </div>
            <div class="description">
              <span><%= t "views.books.shows.description" %></span>
              <span><%= author.description %></span>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

lib_manager/app/views/users/_block_user.html.erb
<% users.each do |user| %>
  <%= link_to user_path user do %>
    <div class="block">
      <div class="image">
        <%= image_for user, size: Settings.size_avatar %>
      </div>
      <div class="name">
        <%= user.name %>
      </div>
    </div>
  <% end %>
<% end %>

lib_manager/app/views/users/_follow_form.html.erb
<% unless current_user.current_user? @user %>
  <div class="follow-form-user">
    <%= render current_user.following_user?(@user) ? "unfollow_user" : "follow_user" %>
  </div>
<% end %>

lib_manager/app/views/users/_follow_user.html.erb
<%= form_for :following_user, url:  user_follow_users_path(current_user),
  remote: true do |f| %>
  <%= hidden_field_tag :follower_id, @user.id %>
  <%= f.submit t("views.users.shows.btn_follow"), class: "btn btn-success" %>
<% end %>

lib_manager/app/views/users/_form_user.html.erb
<%= form_for @user do |f| %>
  <%= render "/shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t("views.user.signup.confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>

  <%= f.label :phonenumber %>
  <%= f.number_field :phonenumber, class: "form-control" %>

  <%= f.file_field :image %>

  <%= f.submit yield(:button_text) , class: "btn btn-primary" %>
<% end %>

lib_manager/app/views/users/_list_book.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t "views.users.shows.list_books.book_name" %></th>
      <th><%= t "views.users.shows.list_books.date_borrow" %></th>
      <th><%= t "views.users.shows.list_books.date_return" %></th>
      <th><%= t "views.users.shows.list_books.date_status" %></th>
      <th><%= t "views.users.shows.list_books.reserve_day" %></th>
    </tr>
  </thead>
  <tbody>
    <% @borrow_books.each do |borrow_book| %>
      <tr>
        <td><%= borrow_book.book.name %></td>
        <td><%= borrow_book.date_borrow %></td>
        <td><%= borrow_book.date_return %></td>
        <td>
          <%= t "views.users.shows.list_books.#{borrow_book.status}" %>
        </td>
        <td>
          <%= reserve_day borrow_book %>
        </td>
        <td>
        <% unless borrow_book.borrowing? %>
          <td>
            <%= link_to user_borrow_book_path(current_user, borrow_book),
              method: :delete do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

lib_manager/app/views/users/_unfollow_user.html.erb
<%= form_for :unfollow_book, url: user_follow_user_path(user_id: current_user.id,
  id: @user.id), method: :delete, remote: true do |f| %>
  <%= f.submit t("views.users.shows.btn_unfollow"), class: "btn btn-danger" %>
<% end %>

lib_manager/app/views/users/_user_follow.html.erb
<ul class="nav nav-tabs nav-justified">
  <li><%= link_to t("views.user.shows.user_following"),
    user_path(@user, relationship: "following"), remote: true %></li>
  <li><%= link_to t("views.user.shows.user_follower"),
    user_path(@user, relationship: "followers"), remote: true %></li>
</ul>
<div class="list-user">
  <%= render "users/block_user", users: @users %>
  <%= will_paginate @users %>
</div>

lib_manager/app/views/users/edit.html.erb
<% provide :title, t("views.user.edits.edit_user") %>
<% provide :button_text, t("views.user.edits.save") %>
<div id="edit-user" class="user-form">
  <h1><%= t "views.user.edits.profile" %></h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form_user" %>
    </div>
  </div>
</div>

lib_manager/app/views/users/new.html.erb
<% provide :title, t("views.user.signup.sign_up") %>
<% provide :button_text, t("views.user.signup.create_user") %>

<div id="new_form" class="user-form">
  <h1><%= t "views.user.signup.sign_up"%></h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form_user" %>
    </div>
  </div>
</div>

lib_manager/app/views/users/show.html.erb
<% provide :title, @user.name %>
<div id="user-show">
  <div class="user-profile col-xs-3">
    <div class="avatar">
      <%= image_for @user %>
    </div>
    <div class="name">
      <span><%= t "views.user.shows.name" %></span>
      <%= @user.name %>
    </div>
    <div class="address">
      <span><%= t "views.user.shows.address" %></span>
      <%= @user.address %>
    </div>
    <section class="stats">
      <%= render "shared/stats", object: @user %>
    </section>
    <div class="form-follow">
      <%= render "follow_form" %>
    </div>
  </div>
  <div class="user-content col-xs-9">
    <ul class="nav nav-tabs">
      <li class="active">
        <a data-toggle="tab" href="#home"><%= t "views.users.shows.borrow_book" %></a>
      </li>
      <li>
        <a data-toggle="tab" href="#tab1"><%= t "views.users.shows.book_followed" %></a>
      </li>
      <li>
        <a data-toggle="tab" href="#tab2"><%= t "views.users.shows.user_follow" %></a>
      </li>
      <li>
        <a data-toggle="tab" href="#tab3"><%= t "views.users.shows.author_followed" %></a>
      </li>
    </ul>
    <div class="tab-content">
      <div id="home" class="tab-pane fade in active">
        <div class="borrow-book">
          <div class="title">
            <h3><%= t "views.users.shows.list_book_borrowing" %></h3>
          </div>
          <div class="list-book">
            <%= render "list_book" %>
          </div>
        </div>
      </div>
      <div id="tab1" class="tab-pane fade">
        <div class="following-books">
          <div class="title">
            <h3><%= t "views.users.shows.list_book_following" %></h3>
          </div>
          <div class="list-books">
            <%= render "/books/list_items" %>
            <% will_paginate @books %>
          </div>
        </div>
      </div>
      <div id="tab2" class="tab-pane fade">
        <div class="user-follow">
          <div class="title">
            <h3><%= t "views.users.shows.user_follow" %></h3>
          </div>
          <div class="list-users">
            <%= render "user_follow" %>
          </div>
        </div>
      </div>
      <div id="tab3" class="tab-pane fade">
        <div class="author-followed">
          <div class="title">
            <h3><%= t "views.users.shows.author_followed" %></h3>
          </div>
          <%= render "author_followed" %>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix">
  </div>
</div>

lib_manager/app/views/users/show.js.erb
$('.list-user').html('<%= j render "block_user", users: @users %>')