lib_manager/config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get "/pages/*page", to: "pages#show"

  get "signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, expert: [:index, :new] do
    resources :borrow_books, only: [:create, :destroy]
    resources :follow_books, only: [:create, :destroy]
    resources :follow_users, only: [:index, :create, :destroy]
    resources :follow_authors, only: [:create, :destroy]
    resources :ratings, only: [:create, :update]
  end
  resources :authors, only: :show
  resources :books, only: [:index, :show] do
    resources :comments, only: :create
  end
  resources :categories, only: :show do
    resources :books, only: [:index, :show]
  end

  namespace :admins do
    resources :users
    resources :books
    resources :publishers
    resources :authors
    resources :categories
    resources :borrow_books, only: [:index, :update, :destroy]
  end
end

lib_manager/app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
  has_many :authors

  scope :sort_by_create_at, -> {order created_at: :desc}
  scope :search_by_name, -> search {where "name LIKE ?", "%#{search}%"}

  class << self
    def to_csv options = {}
      CSV.generate options do |csv|
        csv << column_names
        all.each do |publisher|
          csv << publisher.attributes.values_at(*column_names)
        end
      end
    end
  end
end

lib_manager/app/controllers/admins/publishers_controller.rb
class Admins::PublishersController < ApplicationController
  layout "application_admin"

  before_action :logged_in_user, :verify_admin
  before_action :find_user, except: [:index, :new, :create]
  before_action :load_data, only: [:new, :edit]

  def index
    @publishers = if params[:search].present?
      Publisher.search_by_name(params[:search])
    else
      Publisher
    end.sort_by_create_at.paginate page: params[:page]
    respond_to do |format|
      format.html
      format.js
      format.xls {send_data @publishers.to_csv(col_sep: "\t")}
    end
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new publisher_params
    if @publisher.save
      flash[:success] = t "controllers.publishers.publisher_create"
      redirect_to admins_publishers_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @publisher.update_attributes publisher_params
      redirect_to admins_publishers_path
      flash[:success] = t "controllers.publishers.publisher_edit"
    else
      render :edit
    end
  end

  def destroy
    @publisher.destroy
    flash[:success] = t "controllers.publishers.publisher_delete"
    redirect_to admins_publishers_path 
  end

  private
  def find_user
    @publisher = Publisher.find_by id: params[:id]
    unless @publisher
      flash[:danger] = t "controllers.publishers.publisher_not_exist"
      redirect_to admins_publishers_path
    end
  end

  def publisher_params
    params.require(:publisher).permit :name, :address, :phone,
      :description, :book_ids
  end

  def load_data
    @supports = Supports::Relationship.new
  end
end

lib_manager/app/views/admins/publishers/_form.html.erb
<%= form_for [:admins, @publisher] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :name, t("views.form_publisher.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :address, t("views.form_publisher.address"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :address, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :phone, t("views.form_publisher.phone"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :phone, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :description, t("views.form_publisher.des"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.text_area :description, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :books, t("views.form_book.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
        <%= f.select :book_ids, @supports.books %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :authors, t("views.form_author.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.select :author_ids, @supports.authors %>
        </div> 
      </div>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
          <%= f.submit yield(:button_text), class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

lib_manager/app/views/admins/publishers/_list_publisher.html.erb
<thead>
  <tr>
    <th><%= t "views.form_publisher.name" %></th>
    <th><%= t "views.form_publisher.address" %></th>
    <th><%= t "views.form_publisher.phone" %></th>
    <th><%= t "views.form_publisher.des" %></th>
    <th><%= t "views.form_book.name" %></th>
    <th><%= t "views.form_author.name" %></th>
    <th class="action"></th>
  </tr>
</thead>
<tbody>
  <% @publishers.each do |publisher| %>
    <tr class="background-tr">
      <td><%= publisher.name %></td>
      <td><%= publisher.address %></td>
      <td><%= publisher.phone %></td>
      <td><%= publisher.description %></td>
      <td>
        <ul class="text-left">
          <% publisher.books.each do |book| %>
            <li><%= book.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul class="text-left">
          <% publisher.authors.each do |author| %>
            <li><%= author.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <%= link_to edit_admins_publisher_path publisher do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
        <%= link_to admins_publisher_path(publisher), method: :delete,
          data: {confirm: t("views.form.confirm")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>

lib_manager/app/views/admins/publishers/edit.html.erb
<% provide :title, t("views.users.edits.edit_publisher") %>
<% provide :button_text, t("views.users.edits.save") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.users.edits.edit_publisher" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to new_admins_publisher_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              <%= t "views.user.create" %>
            <% end %>
          </li>
          <li>
            <%= link_to admins_publishers_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "views.user.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form" %>
    </div>
  </div>
</div>

lib_manager/app/views/admins/publishers/index.html.erb
<% provide :title, t("views.users.show_publisher") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.users.show_publisher" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to new_admins_publisher_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              <%= t "views.users.create" %>
            <% end %>
          </li>
          <li>
            <%= link_to admins_publishers_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "views.users.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="row wrap-search">
      <div class="col-md-6 col-md-offset-6">
        <%= form_tag admins_publishers_path, method: :get, remote: true do %>
          <div class="form-group pull-right">
            <%= text_field_tag :search, params[:search], placeholder: t("views.input.value") %>
            <%= submit_tag t("views.search"), class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <%= render "list_publisher" %>
      </table>
      <div class="pagination">
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

lib_manager/app/views/admins/publishers/index.js.erb
$('.table').html('<%= j render "list_publisher" %>');
$('.pagination').html('<%= j will_paginate @publishers %>');

lib_manager/app/views/admins/publishers/new.html.erb
<% provide :title, t("views.users.signup.create_publisher") %>
<% provide :button_text, t("views.users.signup.create_publisher") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.users.signup.create_publisher" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to admins_publishers_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "views.users.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form" %>
    </div>
  </div>
</div>