lib_manager/config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get "/pages/*page", to: "pages#show"

  get "signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, expert: [:index, :new] do
    resources :borrow_books, only: [:create, :destroy]
    resources :follow_books, only: [:create, :destroy]
    resources :follow_users, only: [:index, :create, :destroy]
    resources :follow_authors, only: [:create, :destroy]
    resources :ratings, only: [:create, :update]
  end
  resources :authors, only: :show
  resources :books, only: [:index, :show] do
    resources :comments, only: :create
  end
  resources :categories, only: :show do
    resources :books, only: [:index, :show]
  end

  namespace :admins do
    resources :users
    resources :books
    resources :publishers
    resources :authors
    resources :categories
    resources :borrow_books, only: [:index, :update, :destroy]
  end
end

lib_manager/app/models/category.rb
class Category < ApplicationRecord
  has_many :relationships, as: :ownerable
  has_many :books, through: :relationships,
    source_type: Book.name, source: :targetable

  scope :sort_by_create_at, -> {order created_at: :desc}
  scope :search_by_name, -> search {where "name LIKE ?", "%#{search}%"}

  class << self
    def to_csv options = {}
      CSV.generate options do |csv|
        csv << column_names
        all.each do |category|
          csv << category.attributes.values_at(*column_names)
        end
      end
    end
  end
end

lib_manager/app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
  layout "application_admin"

  before_action :logged_in_user, :verify_admin
  before_action :find_category, except: [:index, :new, :create]
  before_action :load_data, only: [:new, :edit]

  def index
    @categories = if params[:search].present?
      Category.search_by_name(params[:search])
    else
      Category
    end.sort_by_create_at.paginate page: params[:page]
    respond_to do |format|
      format.html
      format.js
      format.xls {send_data @categories.to_csv(col_sep: "\t")}
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "controllers.categories.category_create"
      redirect_to admins_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      redirect_to admins_categories_path
      flash[:success] = t "controllers.categories.category_edit"
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "controllers.categories.category_delete"
    else
      flash[:danger] = t "controllers.categories.wrong_category"
    end
    redirect_to admins_categories_path 
  end

  private
  def find_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "controllers.books.category_not_exist"
      redirect_to admins_categories_path
    end
  end

  def category_params
    params.require(:category).permit :name, :book_ids
  end

  def load_data
    @supports = Supports::Relationship.new
  end
end

lib_manager/app/views/admins/categories/_form.html.erb
<%= form_for [:admins, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3"">
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :name, t("views.form_category.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :books, t("views.form_book.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
        <%= f.select :book_ids, @supports.books %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
          <%= f.submit yield(:button_text), class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

lib_manager/app/views/admins/categories/_list_category.html.erb
<thead>
  <tr>
    <th><%= t "views.form_category.id" %></th>
    <th><%= t "views.form_book.name" %></th>
    <th><%= t "views.form_category.name" %></th>
    <th class="action"></th>
  </tr>
</thead>
<tbody>
  <% @categories.each do |category| %>
    <tr class="background-tr">
      <td><%= category.id %></td>
      <td>
        <ul class="text-left">
          <% category.books.each do |book| %>
            <li><%= book.name %></li>
          <% end %>
        </ul>
      </td>
      <td><%= category.name %></td>
      <td>
        <%= link_to edit_admins_category_path category do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
        <%= link_to admins_category_path(category), method: :delete,
          data: {confirm: t("views.form.confirm")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>

lib_manager/app/views/admins/categories/edit.html.erb
<% provide :title, t("views.users.edits.edit_category") %>
<% provide :button_text, t("views.users.edits.save") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.users.edits.edit_category" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to new_admins_category_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              <%= t "views.user.create" %>
            <% end %>
          </li>
          <li>
            <%= link_to admins_categories_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "views.user.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form" %>
    </div>
  </div>
</div>

lib_manager/app/views/admins/categories/index.html.erb
<% provide :title, t("views.users.show_list_category") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.users.show_list_category" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to new_admins_category_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              <%= t "views.user.create" %>
            <% end %>
          </li>
          <li>
            <%= link_to admins_categories_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "views.user.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="row wrap-search">
      <div class="col-md-6 col-md-offset-6">
        <%= form_tag admins_categories_path, method: :get, remote: true do %>
          <div class="form-group pull-right">
            <%= text_field_tag :search, params[:search], placeholder: t("views.input.value") %>
            <%= submit_tag t("views.search"), class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <%= render "list_category" %>
      </table>
      <div class="pagination">
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

lib_manager/app/views/admins/categories/index.js.erb
$('.table').html('<%= j render "list_category" %>');
$('.pagination').html('<%= j will_paginate @categories %>');

lib_manager/app/views/admins/categories/new.html.erb
<% provide :title, t("views.users.signup.create_category") %>
<% provide :button_text, t("views.users.signup.create_category") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.users.signup.create_category" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to admins_categories_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "views.user.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form" %>
    </div>
  </div>
</div>