lib_manager/config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get "/pages/*page", to: "pages#show"

  get "signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, expert: [:index, :new] do
    resources :borrow_books, only: [:create, :destroy]
    resources :follow_books, only: [:create, :destroy]
    resources :follow_users, only: [:index, :create, :destroy]
    resources :follow_authors, only: [:create, :destroy]
    resources :ratings, only: [:create, :update]
  end
  resources :authors, only: :show
  resources :books, only: [:index, :show] do
    resources :comments, only: :create
  end
  resources :categories, only: :show do
    resources :books, only: [:index, :show]
  end

  namespace :admins do
    resources :users
    resources :books
    resources :publishers
    resources :authors
    resources :categories
    resources :borrow_books, only: [:index, :update, :destroy]
  end
end

lib_manager/app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <p><%= t "views.footer.made_by" %></p>
    <nav>
      <ul>
        <li><%= link_to t("views.footer.about"), "#" %></li>
        <li><%= link_to t("views.footer.contact"), "#" %></li>
      </ul>
    </nav>
  </div>
</footer>

lib_manager/app/views/layouts/_footer_admin.html.erb
<div class="footer">
  <div class="container">
    <span>
      &copy;
      <%= t "views.footer_admin.copy_right" %>
      <%= link_to "#" do %>
        <%= t "views.footer_admin.name_team" %>
      <% end %>
    </span>
  </div>
</div>

lib_manager/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" id="header">
  <div class="container">
    <div class="brand side-left col-xs-2">
      <%= link_to image_tag("logo.png", size: Settings.size_logo), root_path %>
    </div>
    <nav class="side-right col-xs-10">
      <div class="form-search">
        <%= form_for :search, url: books_path, method: "get" do |f| %>
          <%= f.text_field :book_name, placeholder: t("views.header.placeholder") %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right list-item">
        <% if logged_in? %>
          <% if current_user.is_admin? %>
            <li><%= link_to t("views.header.admin"), admins_users_path %></li>
          <% end %>
          <li><%= link_to t("views.header.home"), root_path %></li>
          <li><%= link_to t("views.header.my_profile"), current_user %></li>
          <li><%= link_to t("views.header.list_book"), books_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("views.header.profile"), current_user %></li>
              <li><%= link_to t("views.header.setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("views.header.logout"), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("views.header.home"), "#" %></li>
          <li><%= link_to t("views.header.list_book"), books_path %></li>
          <li><%= link_to t("views.header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
    <div class="clearfix"></div>
  </div>
</header>

lib_manager/app/views/layouts/_header_admin.html.erb
<div class="header">
  <div class="container">
    <div class="logo pull-left">
      <%= link_to image_tag("logo.png"), "#" %>
    </div>
    <div class="account pull-right">
      <div class="username">
        <%= link_to "#" do %>
          <span>
            <%= current_user.name %>
            <i class="glyphicon glyphicon-triangle-bottom"></i>
          </span>
        <% end %>
      </div>
      <ul>
        <li>
          <%= link_to logout_path, method: "delete" do %>
            <i class="glyphicon glyphicon-log-out"></i>
            <%= t "views.menu.logout" %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="menu-header">
  <div class="container">
    <div class="menu-left">
      <ul>
        <li>
          <%= link_to root_path do %>
            <i class="glyphicon glyphicon-home"></i>
            <%= t "views.menu.home" %>
          <% end %>
        </li>
        <li class="<%= "actived" if current_page?(admins_users_path) %>">
          <%= link_to t("views.menu.manager_user"), admins_users_path %></li>
        <li class="<%= "actived" if current_page?(admins_books_path) %>">
          <%= link_to t("views.menu.manager_book"), admins_books_path %></li>
        <li class="<%= "actived" if current_page?(admins_publishers_path) %>">
          <%= link_to t("views.menu.manager_publisher"), admins_publishers_path %></li>
        <li class="<%= "actived" if current_page?(admins_authors_path) %>">
          <%= link_to t("views.menu.manager_author"), admins_authors_path %></li>
        <li class="<%= "actived" if current_page?(admins_categories_path) %>">
          <%= link_to t("views.menu.manager_category"), admins_categories_path %></li>
        <li><%= link_to t("views.menu.manager_borrow"), admins_borrow_books_path %></li>
      </ul>
    </div>
  </div>
</div>

lib_manager/app/views/layouts/_modal.html.erb
<div class="modal fade" id="book_modal_<%= book.id %>" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <%= button_tag class: "close", "data-dismiss" => "modal" do %>
          &times;
        <% end %>
        <h4 class="modal-title"><%= t "views.modal.title_details" %></h4>
      </div>
      <div class="row">
        <div class="col-md-5">
          <%= image_tag book.image, class: "size-img-modal" %>
        </div>
        <div class="col-md-7">
          <div class="info-book">
            <p><%= t "views.form_book.id" %>:&nbsp;
              <%= book.id %></p>
            <p><%= t "views.form_book.name" %>:&nbsp;
              <%= book.name %></p>
            <p><%= t "views.form_book.publisher_year" %>:&nbsp;
              <%= book.publisher_year %></p>
            <p><%= t "views.form_book.amount" %>:&nbsp;
              <%= book.amount %></p>
            <p><%= t "views.form_book.weight" %>:&nbsp;
              <%= book.weight %></p>
            <p><%= t "views.form_book.language" %>:&nbsp;
              <%= book.language %></p>
            <p><%= t "views.form_publisher.name" %>:&nbsp;
              <%= link_to "#" do %>
                <%= book.publisher.name %>
              <% end %>
            </p>
            <p><%= t "views.form_author.name" %>:&nbsp;
              <%= link_to "#" do %>
                <% book.authors.each do |author| %>
                  <%= author.name %>
                <% end %>
              <% end %>
            </p>
            <p><%= t "views.form_category.name" %>:&nbsp;
              <%= link_to "#" do %>
                <% book.categories.each do |category| %>
                  <%= category.name %>
                <% end %>
              <% end %>
            </p>
         </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="info-book">
            <p><%= t "views.form_book.description" %>:&nbsp;
              <%= book.description %></p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= button_tag class: "btn btn-default", "data-dismiss" => "modal" do %>
          <%= t "views.modal.close" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

lib_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="main-body">
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <%= render "/layouts/footer" %>
  </body>
</html>

lib_manager/app/views/layouts/application_admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header_admin" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render "/layouts/footer_admin" %>
  </body>
</html>